# Generated by Django 3.2.25 on 2025-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
